export enum SpaceType {
    Property,
    RailRoad,
    GoToJail,
    Start,
    Jail,
    FreeParking,
    Chance,
    IncomeTax,
    CommunityChest,
    Services,
    LuxuryTax
}

export const gameConfig = [
    {"id": 0, "name": "Start", "rentValue": null, "colorCode": "#ffffff", "type": SpaceType.Start},
    {"id": 1, "name": "Mediterranean Avenue", "rentValue": 60, "colorCode": "#955436", "type": SpaceType.Property},
    {"id": 1, "name": "Community Chest", "rentValue": 100, "colorCode": "", "type": SpaceType.CommunityChest},
    {"id": 1, "name": "Baltic Avenue", "rentValue": 60, "colorCode": "#955436", "type": SpaceType.Property},
    {"id": 1, "name": "Income Tax", "rentValue": null, "colorCode": "", "type": SpaceType.IncomeTax},
    {"id": 1, "name": "Reading Railroad", "rentValue": null, "colorCode": "", "type": SpaceType.RailRoad},
    {"id": 1, "name": "Oriental Avenue", "rentValue": 100, "colorCode": "#aae0fa", "type": SpaceType.Property},
    {"id": 1, "name": "Chance", "rentValue": null, "colorCode": "", "type": SpaceType.Chance},
    {"id": 1, "name": "Vermont Avenue", "rentValue": 100, "colorCode": "#aae0fa", "type": SpaceType.Property},
    {"id": 1, "name": "Connecticut Avenue", "rentValue": 110, "colorCode": "#aae0fa", "type": SpaceType.Property},
    {"id": 1, "name": "Jail", "rentValue": null, "colorCode": "", "type": SpaceType.Jail},
    {"id": 1, "name": "St. Charles place", "rentValue": 140, "colorCode": "#d93a96", "type": SpaceType.Property},
    {"id": 1, "name": "electric company", "rentValue": null, "colorCode": "", "type": SpaceType.Services},
    {"id": 1, "name": "States Avenue", "rentValue": 140, "colorCode": "#d93a96", "type": SpaceType.Property},
    {"id": 1, "name": "Virginia avenue", "rentValue": 160, "colorCode": "#d93a96", "type": SpaceType.Property},
    {"id": 1, "name": "pennsylvania railroad", "rentValue": null, "colorCode": "", "type": SpaceType.RailRoad},
    {"id": 1, "name": "St. James place", "rentValue": 180, "colorCode": "#f7941d", "type": SpaceType.Property},
    {"id": 1, "name": "community chest", "rentValue": null, "colorCode": "", "type": SpaceType.CommunityChest},
    {"id": 1, "name": "tennessee avenue", "rentValue": 180, "colorCode": "#f7941d", "type": SpaceType.Property},
    {"id": 1, "name": "new york avenue", "rentValue": 200, "colorCode": "#f7941d", "type": SpaceType.Property},
    {"id": 1, "name": "Free parking", "rentValue": null, "colorCode": "", "type": SpaceType.FreeParking},
    {"id": 1, "name": "Kentucky avenue", "rentValue": 220, "colorCode": "#ed1b24", "type": SpaceType.Property},
    {"id": 1, "name": "chance", "rentValue": null, "colorCode": "", "type": SpaceType.Chance},
    {"id": 1, "name": "indiana avenue", "rentValue": 220, "colorCode": "#ed1b24", "type": SpaceType.Property},
    {"id": 1, "name": "illinois avenue", "rentValue": 240, "colorCode": "#ed1b24", "type": SpaceType.Property},
    {"id": 1, "name": "B & O Railroad", "rentValue": null, "colorCode": "", "type": SpaceType.RailRoad},
    {"id": 1, "name": "Atlantic avenue", "rentValue": 260, "colorCode": "#fef200", "type": SpaceType.Property},
    {"id": 1, "name": "ventnor avenue", "rentValue": 260, "colorCode": "#fef200", "type": SpaceType.Property},
    {"id": 1, "name": "Water works", "rentValue": null, "colorCode": "", "type": SpaceType.Services},
    {"id": 1, "name": "marvin gardens", "rentValue": 280, "colorCode": "#fef200", "type": SpaceType.Property},
    {"id": 1, "name": "Go To Jail", "rentValue": null, "colorCode": "", "type": SpaceType.GoToJail},
    {"id": 1, "name": "Pacific avenue", "rentValue": 300, "colorCode": "#1fb25a", "type": SpaceType.Property},
    {"id": 1, "name": "North carolina avenue", "rentValue": 300, "colorCode": "#1fb25a", "type": SpaceType.Property},
    {"id": 1, "name": "community chest", "rentValue": null, "colorCode": "", "type": SpaceType.CommunityChest},
    {"id": 1, "name": "pennsylvania avenue", "rentValue": 320, "colorCode": "#1fb25a", "type": SpaceType.Property},
    {"id": 1, "name": "Short Line railroad", "rentValue": null, "colorCode": "", "type": SpaceType.RailRoad},
    {"id": 1, "name": "chance", "rentValue": null, "colorCode": "", "type": SpaceType.Chance},
    {"id": 1, "name": "park place", "rentValue": 350, "colorCode": "#0072bb", "type": SpaceType.Property},
    {"id": 1, "name": "Luxury Tax", "rentValue": null, "colorCode": "", "type": SpaceType.LuxuryTax},
    {"id": 1, "name": "Broadwalk", "rentValue": 400, "colorCode": "#0072bb","type": SpaceType. Property}
]